### ISSUE TITLE
Encontrar item na imagem

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#190]
## Jogo de encontrar itens na tela

- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
*Users e Admins*

- Breve história da issue
Por meio de usuário administrador quero criar uma questão de procurar itens na tela a partir de um upload.

- Definition of done
- [ ] Novo tipo de questão hiddenObjects
- [ ] Armazenar localização dos objetos na resposta da pergunta -> Aqui se armazena uma região que será de 25x25px
- [ ] A imagem deve com resolução mínima de 1000x1000px
- [ ] A exibição da questão para student deve ampliar a imagem mostrando apenas 1/5 da imagem na tela em mobile, 1/4 em tablet e 1/1 em desktop
- [ ] Ao clicar em alguma parte da tela se abre um dropdown que o usuário deve escolher qual objeto encontrou. Esse objeto deve estar dentro da região selecionada
- [ ] Se encontrar um objeto ele some da lista de opções
